# -*- coding: utf-8 -*-
"""PromtEngineer_localGPT_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gAPlihLbTb0P1QWqeMHqJhtqlWjPTVMp
"""

!git clone https://github.com/PromtEngineer/localGPT.git

!pip install -q condacolab
import condacolab
condacolab.install()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !conda create -n localGPT python=3.10.0
# !conda activate localGPT

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -r ./localGPT/requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # If you want to start from an empty database, delete the DB and reingest your documents.
# !python ./localGPT/ingest.py

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install llama-cpp-python

!python localGPT/run_localGPT.py